set(source_root "${PROJECT_SOURCE_DIR}")
file(READ "${source_root}/clicker.cpp" clicker_cpp)

function(require_not_contains text pattern message)
    string(FIND "${text}" "${pattern}" match_index)
    if(NOT match_index EQUAL -1)
        message(FATAL_ERROR "${message}: found '${pattern}'")
    endif()
endfunction()

function(require_contains text pattern message)
    string(FIND "${text}" "${pattern}" match_index)
    if(match_index EQUAL -1)
        message(FATAL_ERROR "${message}: missing '${pattern}'")
    endif()
endfunction()

require_not_contains("${clicker_cpp}" "setPalette(QApplication::palette())" "Do not force application palette onto widgets")
require_not_contains("${clicker_cpp}" "changelogButton->setStyleSheet" "Top bar buttons must keep native Qt/KDE styling")
require_not_contains("${clicker_cpp}" "settingsButton->setStyleSheet" "Top bar buttons must keep native Qt/KDE styling")
require_not_contains("${clicker_cpp}" "statsLabel->setStyleSheet" "Stats label must use QFont instead of stylesheet")

require_contains("${clicker_cpp}" "QEvent::PaletteChange" "Theme icon refresh must handle palette changes")
require_contains("${clicker_cpp}" "QEvent::ApplicationPaletteChange" "Theme icon refresh must handle application palette changes")
require_contains("${clicker_cpp}" "QEvent::StyleChange" "Theme icon refresh must handle style changes")
require_contains("${clicker_cpp}" "QTimer::singleShot(0, this, &Clicker::applyThemeIcons)" "Theme icon refresh must run after Qt applies the palette")
require_contains("${clicker_cpp}" "QTimer::singleShot(100, this, &Clicker::applyThemeIcons)" "Theme icon refresh must handle delayed KDE style propagation")

string(REGEX MATCHALL "#[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]([0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f])?" hex_colors "${clicker_cpp}")
set(allowed_colors "#2e7d32" "#ef6c00" "#777")
foreach(color IN LISTS hex_colors)
    if(NOT color IN_LIST allowed_colors)
        message(FATAL_ERROR "Unexpected hardcoded color in clicker.cpp: ${color}")
    endif()
endforeach()
